### ISSUE TITLE
'DXMessageBoxService' does not exist in XML namespace 'http://schemas.devexpress.com/winfx/2008/xaml/core' Line 13 Position 10.	

### ISSUE THREAD

**Issue by iotjack** [DevExpress-Examples/how-to-use-the-poco-mechanism-e5167#1]
does this still work? I'm interested to try out POCO viewmodel and followed this example. But I keep getting the error with the DXMessageBoxService, with both .net and .net core. I also tried different version of DevExpress.MVVM (17 vs latest 20).

**Comment by ivansupport** [comment]
Hello,

This example supports version 20.1 and should work if you use the complete DevExpress installation available at [Download Free Trial](https://www.devexpress.com/Products/Try/) (for trial customers) or [Download Your Products](https://www.devexpress.com/ClientCenter/DownloadManager/) (for licensed customers).

If you're using the [free version of our MVVM Framework](https://github.com/DevExpress/DevExpress.Mvvm.Free), the `DXMessageBoxService` class is not available there. You can create a [custom service](https://docs.devexpress.com/WPF/16920/mvvm-framework/services/how-to-create-a-custom-service), attach it to your View, and invoke its methods at the ViewModel level.

Should you face difficulties with this approach, feel free to create a ticket in our [Support Center](https://supportcenter.devexpress.com).
